### ISSUE TITLE
copies again if issues are moved to different list..

### ISSUE THREAD

**Issue by thinkong** [cprice404/redmine-trello#10]
once i copy stuff from redmine to trello.. 
then i move cards from a list to another.. 

then when i do a cronjob.. it will re copy the moved cards again.. anyway this can be fixed?

**Comment by cprice404** [comment]
It only copies cards that are in the state that you specify in the config file (e.g., "Unreviewed").  If you change the status in Redmine it won't make any additional copies.

This is considered a feature by some users of this tool, so if we were going to change the behavior I think that it would need to be a configurable option.

**Comment by joeyates** [comment]
Hello, thanks for the useful project.
@thinkong: I had the same requirement, which I have made in my fork: https://github.com/joeyates/redmine-trello/commit/2dd3b577184c53c24a64cfdfe88deb1362e99cad
@cprice-puppet: I'll make this change a config option and sort out a pull request.

**Comment by cprice404** [comment]
@joeyates great, thanks!

**Comment by joeyates** [comment]
I think we can say this is closed by https://github.com/cprice-puppet/redmine-trello/commit/fdd1641e0c9034b300ba10c5018b6313af975aa7

**Comment by cprice404** [comment]
Thanks!
