### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by zeroasterisk** [cprice404/redmine-trello#5]
Can you please provide some installation documentation?

What versions of Redmine are supported?

What features are currently developed?  What are planned?

(ha! do you have a link to a trello plan board on this?)

**Comment by cprice404** [comment]
Added a README that answers your first 2 questions.  As to your remaining questions: we do not have any immediate plans to extend this much further.  We're using it internally at Puppet Labs, and just adding on new things as we see a need for them.  So, no Trello planning board for the project :)

Thanks!

**Comment by zeroasterisk** [comment]
thanks mate!
