### ISSUE TITLE
AuthPolicy error in trello.rb

### ISSUE THREAD

**Issue by WindingWhisper** [cprice404/redmine-trello#7]
When executing copy_to_trello.rb I receive the following error and am unable to resolve it:

/root/redmine-trello/lib/rmt/trello.rb:14: warning: already initialized constant AuthPolicy

This is likely something silly on my end, but I'm a ruby noob and I'm struggling with this one.

Ruby version: 1.9.3p194

**Comment by cprice404** [comment]
That message is actually just a warning, and shouldn't cause any failures.  If the script is failing later, do you see any other error messages?

**Comment by WindingWhisper** [comment]
That was the only message I received; I wasn't able to get my redmine stuff ported over to Trello unfortunately (the scripts executed fine, but nothing came over to Trello). Our version of redmine is much newer than 1.3, so that could be the issue.

It's moot at this point, we've opted to build an in-house alternative to Trello.

Thanks!
